import { ProjectInfo } from './projectDetector';

export interface DeployOptions {
    serverUser: string;
    serverHost: string;
    serverPort: number;
    deployPath: string;
    useDocker: boolean;
    usePM2: boolean;
    useCertbot: boolean;
}

export class DeployScriptGenerator {
    
    // 生成部署脚本
    generateDeployScript(project: ProjectInfo, options: DeployOptions): string {
        if (options.useDocker) {
            return this.generateDockerDeployScript(project, options);
        }
        return this.generateTraditionalDeployScript(project, options);
    }

    // 生成传统部署脚本
    private generateTraditionalDeployScript(project: ProjectInfo, options: DeployOptions): string {
        return `#!/bin/bash

# =============================================================================
# ${project.name} 部署脚本
# Framework: ${project.framework}
# Generated by Nginx Config Generator
# =============================================================================

set -e

# 配置变量
PROJECT_NAME="${project.name}"
SERVER_USER="${options.serverUser}"
SERVER_HOST="${options.serverHost}"
SERVER_PORT="${options.serverPort || 22}"
DEPLOY_PATH="${options.deployPath || '/var/www/' + project.name}"
BUILD_DIR="${project.buildDir}"
NGINX_CONF="/etc/nginx/conf.d/\${PROJECT_NAME}.conf"

# 颜色输出
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
NC='\\033[0m' # No Color

echo -e "\${GREEN}开始部署 \${PROJECT_NAME}...\${NC}"

# =============================================================================
# 步骤 1: 本地构建
# =============================================================================
echo -e "\${YELLOW}[1/6] 本地构建项目...\${NC}"

if [ -f "package.json" ]; then
    # 安装依赖
    npm ci
    
    # 根据项目类型构建
    case "${project.type}" in
        "react"|"vue"|"angular"|"svelte")
            npm run build
            ;;
        "next")
            npm run build
            ;;
        "nuxt")
            npm run build
            ;;
        *)
            npm run build 2>/dev/null || npm run prod 2>/dev/null || echo "请手动构建"
            ;;
    esac
else
    echo -e "\${RED}错误: 未找到 package.json\${NC}"
    exit 1
fi

# =============================================================================
# 步骤 2: 上传到服务器
# =============================================================================
echo -e "\${YELLOW}[2/6] 上传到服务器...\${NC}"

# 创建远程目录
ssh -p \${SERVER_PORT} \${SERVER_USER}@\${SERVER_HOST} "sudo mkdir -p \${DEPLOY_PATH}"

# 上传构建文件
scp -P \${SERVER_PORT} -r \${BUILD_DIR}/* \${SERVER_USER}@\${SERVER_HOST}:/tmp/\${PROJECT_NAME}_deploy/

# 移动到目标目录
ssh -p \${SERVER_PORT} \${SERVER_USER}@\${SERVER_HOST} << EOF
    sudo rm -rf \${DEPLOY_PATH}/*
    sudo mv /tmp/\${PROJECT_NAME}_deploy/* \${DEPLOY_PATH}/
    sudo chown -R nginx:nginx \${DEPLOY_PATH}
    sudo chmod -R 755 \${DEPLOY_PATH}
EOF

# =============================================================================
# 步骤 3: 配置 Nginx
# =============================================================================
echo -e "\${YELLOW}[3/6] 配置 Nginx...\${NC}"

# 上传 Nginx 配置
scp -P \${SERVER_PORT} nginx.conf \${SERVER_USER}@\${SERVER_HOST}:/tmp/\${PROJECT_NAME}.conf

ssh -p \${SERVER_PORT} \${SERVER_USER}@\${SERVER_HOST} << EOF
    sudo mv /tmp/\${PROJECT_NAME}.conf \${NGINX_CONF}
    sudo nginx -t
    sudo systemctl reload nginx
EOF

# =============================================================================
# 步骤 4: 配置 SSL (可选)
# =============================================================================
${options.useCertbot ? `
echo -e "\${YELLOW}[4/6] 配置 SSL 证书...\${NC}"

ssh -p \${SERVER_PORT} \${SERVER_USER}@\${SERVER_HOST} << EOF
    # 安装 Certbot
    if ! command -v certbot &> /dev/null; then
        sudo apt-get update
        sudo apt-get install -y certbot python3-certbot-nginx
    fi
    
    # 申请证书
    sudo certbot --nginx -d \${SERVER_HOST} --non-interactive --agree-tos --email admin@\${SERVER_HOST}
    
    # 自动续期
    sudo systemctl enable certbot.timer
EOF
` : `
echo -e "\${YELLOW}[4/6] 跳过 SSL 配置...\${NC}"
`}

# =============================================================================
# 步骤 5: 防火墙配置
# =============================================================================
echo -e "\${YELLOW}[5/6] 配置防火墙...\${NC}"

ssh -p \${SERVER_PORT} \${SERVER_USER}@\${SERVER_HOST} << EOF
    sudo ufw allow 'Nginx Full'
    sudo ufw allow 22/tcp
    sudo ufw --force enable
EOF

# =============================================================================
# 步骤 6: 验证部署
# =============================================================================
echo -e "\${YELLOW}[6/6] 验证部署...\${NC}"

# 等待服务启动
sleep 2

# 测试访问
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://\${SERVER_HOST} || echo "000")

if [ "\${HTTP_CODE}" = "200" ] || [ "\${HTTP_CODE}" = "301" ] || [ "\${HTTP_CODE}" = "302" ]; then
    echo -e "\${GREEN}✓ 部署成功!\${NC}"
    echo -e "\${GREEN}  访问地址: http://\${SERVER_HOST}\${NC}"
    ${options.useCertbot ? `echo -e "\${GREEN}  HTTPS地址: https://\${SERVER_HOST}\${NC}"` : ''}
else
    echo -e "\${RED}✗ 部署可能有问题，HTTP 状态码: \${HTTP_CODE}\${NC}"
    echo -e "\${YELLOW}  请检查服务器日志: sudo tail -f /var/log/nginx/error.log\${NC}"
fi

echo ""
echo -e "\${GREEN}部署完成!\${NC}"
`;
    }

    // 生成 Docker 部署脚本
    private generateDockerDeployScript(project: ProjectInfo, options: DeployOptions): string {
        return `#!/bin/bash

# =============================================================================
# ${project.name} Docker 部署脚本
# Framework: ${project.framework}
# Generated by Nginx Config Generator
# =============================================================================

set -e

PROJECT_NAME="${project.name}"
SERVER_USER="${options.serverUser}"
SERVER_HOST="${options.serverHost}"
SERVER_PORT="${options.serverPort || 22}"
DEPLOY_PATH="${options.deployPath || '/opt/' + project.name}"

# 颜色输出
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
NC='\\033[0m'

echo -e "\${GREEN}开始 Docker 部署 \${PROJECT_NAME}...\${NC}"

# =============================================================================
# 步骤 1: 本地构建
# =============================================================================
echo -e "\${YELLOW}[1/5] 本地构建项目...\${NC}"

npm ci
npm run build

# =============================================================================
# 步骤 2: 创建 Dockerfile
# =============================================================================
echo -e "\${YELLOW}[2/5] 创建 Dockerfile...\${NC}"

cat > Dockerfile << 'DOCKEREOF'
# 生产环境 Nginx 镜像
FROM nginx:alpine

# 复制构建文件
COPY ${project.buildDir} /usr/share/nginx/html

# 复制 Nginx 配置
COPY nginx.conf /etc/nginx/conf.d/default.conf

# 创建必要的目录
RUN mkdir -p /var/cache/nginx/client_temp \
    && mkdir -p /var/cache/nginx/proxy_temp \
    && mkdir -p /var/cache/nginx/fastcgi_temp \
    && mkdir -p /var/cache/nginx/uwsgi_temp \
    && mkdir -p /var/cache/nginx/scgi_temp \
    && chown -R nginx:nginx /var/cache/nginx \
    && chown -R nginx:nginx /var/log/nginx \
    && touch /var/run/nginx.pid \
    && chown -R nginx:nginx /var/run/nginx.pid

# 健康检查
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\
    CMD wget --no-verbose --tries=1 --spider http://localhost/nginx-health || exit 1

# 暴露端口
EXPOSE 80

# 使用非 root 用户运行
USER nginx

CMD ["nginx", "-g", "daemon off;"]
DOCKEREOF

# =============================================================================
# 步骤 3: 构建并推送镜像
# =============================================================================
echo -e "\${YELLOW}[3/5] 构建 Docker 镜像...\${NC}"

# 构建镜像
docker build -t \${PROJECT_NAME}:latest .

# 保存镜像并传输到服务器（如果没有 Docker Registry）
docker save \${PROJECT_NAME}:latest | gzip > \${PROJECT_NAME}.tar.gz

# =============================================================================
# 步骤 4: 服务器部署
# =============================================================================
echo -e "\${YELLOW}[4/5] 部署到服务器...\${NC}"

# 上传镜像
scp -P \${SERVER_PORT} \${PROJECT_NAME}.tar.gz \${SERVER_USER}@\${SERVER_HOST}:/tmp/

# 远程执行部署
ssh -p \${SERVER_PORT} \${SERVER_USER}@\${SERVER_HOST} << EOF
    # 安装 Docker（如果未安装）
    if ! command -v docker &> /dev/null; then
        curl -fsSL https://get.docker.com | sh
        sudo usermod -aG docker \${USER}
    fi
    
    # 创建部署目录
    sudo mkdir -p \${DEPLOY_PATH}
    
    # 加载镜像
    sudo docker load < /tmp/\${PROJECT_NAME}.tar.gz
    
    # 停止并删除旧容器
    sudo docker stop \${PROJECT_NAME} 2>/dev/null || true
    sudo docker rm \${PROJECT_NAME} 2>/dev/null || true
    
    # 启动新容器
    sudo docker run -d \\
        --name \${PROJECT_NAME} \\
        --restart unless-stopped \\
        -p 80:80 \\
        ${options.useCertbot ? '-p 443:443 \\' : ''}
        -v \${DEPLOY_PATH}/logs:/var/log/nginx \\
        \${PROJECT_NAME}:latest
    
    # 清理
    rm /tmp/\${PROJECT_NAME}.tar.gz
    sudo docker system prune -f
EOF

# 清理本地文件
rm \${PROJECT_NAME}.tar.gz

# =============================================================================
# 步骤 5: 验证部署
# =============================================================================
echo -e "\${YELLOW}[5/5] 验证部署...\${NC}"

sleep 3

HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://\${SERVER_HOST} || echo "000")

if [ "\${HTTP_CODE}" = "200" ]; then
    echo -e "\${GREEN}✓ Docker 部署成功!\${NC}"
    echo -e "\${GREEN}  访问地址: http://\${SERVER_HOST}\${NC}"
    
    # 查看容器状态
    ssh -p \${SERVER_PORT} \${SERVER_USER}@\${SERVER_HOST} "sudo docker ps | grep \${PROJECT_NAME}"
else
    echo -e "\${RED}✗ 部署可能有问题，HTTP 状态码: \${HTTP_CODE}\${NC}"
    echo -e "\${YELLOW}  查看日志: ssh -p \${SERVER_PORT} \${SERVER_USER}@\${SERVER_HOST} 'sudo docker logs \${PROJECT_NAME}'\${NC}"
fi

echo ""
echo -e "\${GREEN}部署完成!\${NC}"

# 输出管理命令
echo ""
echo "常用命令:"
echo "  查看日志:  ssh -p \${SERVER_PORT} \${SERVER_USER}@\${SERVER_HOST} 'sudo docker logs -f \${PROJECT_NAME}'"
echo "  重启服务:  ssh -p \${SERVER_PORT} \${SERVER_USER}@\${SERVER_HOST} 'sudo docker restart \${PROJECT_NAME}'"
echo "  停止服务:  ssh -p \${SERVER_PORT} \${SERVER_USER}@\${SERVER_HOST} 'sudo docker stop \${PROJECT_NAME}'"
`;
    }

    // 生成 Docker Compose 配置
    generateDockerCompose(project: ProjectInfo, options: DeployOptions): string {
        return `version: '3.8'

services:
  ${project.name}:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${project.name}:latest
    container_name: ${project.name}
    restart: unless-stopped
    ports:
      - "80:80"
${options.useCertbot ? `      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
      - certbot-data:/etc/letsencrypt` : ''}
    networks:
      - ${project.name}-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/nginx-health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

${options.useCertbot ? `
  certbot:
    image: certbot/certbot:latest
    container_name: ${project.name}-certbot
    volumes:
      - certbot-data:/etc/letsencrypt
      - ./html:/usr/share/nginx/html:ro
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait \${!}; done;'"
    networks:
      - ${project.name}-network

volumes:
  certbot-data:
` : ''}

networks:
  ${project.name}-network:
    driver: bridge
`;
    }

    // 生成 GitHub Actions 工作流
    generateGitHubActions(project: ProjectInfo, options: DeployOptions): string {
        return `name: Deploy ${project.name}

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    ${options.useDocker ? `
    - name: Build Docker image
      run: |
        docker build -t ${project.name}:\${{ github.sha }} .
        docker tag ${project.name}:\${{ github.sha }} ${project.name}:latest
        
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: \${{ secrets.SERVER_HOST }}
        username: \${{ secrets.SERVER_USER }}
        key: \${{ secrets.SSH_PRIVATE_KEY }}
        port: ${options.serverPort || 22}
        script: |
          cd ${options.deployPath}
          docker pull ${project.name}:latest
          docker stop ${project.name} || true
          docker rm ${project.name} || true
          docker run -d --name ${project.name} -p 80:80 ${options.useCertbot ? '-p 443:443 ' : ''}${project.name}:latest
    ` : `
    - name: Deploy to server
      uses: appleboy/scp-action@master
      with:
        host: \${{ secrets.SERVER_HOST }}
        username: \${{ secrets.SERVER_USER }}
        key: \${{ secrets.SSH_PRIVATE_KEY }}
        port: ${options.serverPort || 22}
        source: "${project.buildDir}/"
        target: "${options.deployPath}"
        strip_components: 1
        
    - name: Reload Nginx
      uses: appleboy/ssh-action@master
      with:
        host: \${{ secrets.SERVER_HOST }}
        username: \${{ secrets.SERVER_USER }}
        key: \${{ secrets.SSH_PRIVATE_KEY }}
        port: ${options.serverPort || 22}
        script: |
          sudo nginx -t
          sudo systemctl reload nginx
    `}
`;
    }
}
