import { ProjectInfo, ProjectType } from './projectDetector';

export class NginxConfigGenerator {
    
    generate(project: ProjectInfo): string {
        const lines: string[] = [];
        
        lines.push(this.generateHeader(project));
        lines.push('http {');
        lines.push('');
        lines.push(...this.generateBasicHttpConfig().map(l => '    ' + l));
        lines.push('');
        lines.push(...this.generateGzipConfig().map(l => '    ' + l));
        lines.push('');
        lines.push(...this.generateServerBlock(project, 80, false).map(l => '    ' + l));
        lines.push('}');
        
        return lines.join('\n');
    }

    generateAdvanced(project: ProjectInfo, options: any): string {
        const lines: string[] = [];
        
        lines.push(this.generateHeader(project));
        
        if (options.enableLoadBalance && options.upstreamServers) {
            lines.push(...this.generateUpstreamBlock(options));
            lines.push('');
        }
        
        lines.push('http {');
        lines.push('');
        lines.push(...this.generateBasicHttpConfig().map(l => '    ' + l));
        lines.push('');
        
        if (options.enableGzip) {
            lines.push(...this.generateGzipConfig().map(l => '    ' + l));
            lines.push('');
        }
        
        if (options.enableCache) {
            lines.push(...this.generateCacheConfig().map(l => '    ' + l));
            lines.push('');
        }
        
        lines.push(...this.generateAdvancedServerBlock(project, options).map(l => '    ' + l));
        
        if (options.enableHttps) {
            lines.push('');
            lines.push(...this.generateHttpsServerBlock(project, options).map(l => '    ' + l));
        }
        
        lines.push('}');
        
        return lines.join('\n');
    }

    private generateHeader(project: ProjectInfo): string {
        return `# Nginx Configuration for ${project.name}
# Framework: ${project.framework}
# Generated by Nginx Config Generator

user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}`;
    }

    private generateBasicHttpConfig(): string[] {
        return [
            'include /etc/nginx/mime.types;',
            'default_type application/octet-stream;',
            '',
            'log_format main \'$remote_addr - $remote_user [$time_local] "$request" \'',
            '                \'$status $body_bytes_sent "$http_referer" \'',
            '                \'"$http_user_agent" "$http_x_forwarded_for"\';',
            '',
            'access_log /var/log/nginx/access.log main;',
            '',
            'sendfile on;',
            'tcp_nopush on;',
            'tcp_nodelay on;',
            'keepalive_timeout 65;',
            'types_hash_max_size 2048;'
        ];
    }

    private generateGzipConfig(): string[] {
        return [
            '# Gzip 压缩配置',
            'gzip on;',
            'gzip_vary on;',
            'gzip_min_length 1024;',
            'gzip_proxied expired no-cache no-store private auth;',
            'gzip_types',
            '    text/plain',
            '    text/css',
            '    text/xml',
            '    text/javascript',
            '    application/javascript',
            '    application/xml+rss',
            '    application/json;'
        ];
    }

    private generateCacheConfig(): string[] {
        return [
            '# 静态资源缓存配置',
            'map $sent_http_content_type $expires {',
            '    default 1d;',
            '    text/html epoch;',
            '    text/css 7d;',
            '    application/javascript 7d;',
            '    ~image/ 30d;',
            '}',
            '',
            'expires $expires;'
        ];
    }

    private generateServerBlock(project: ProjectInfo, port: number, isHttps: boolean): string[] {
        const lines: string[] = [];
        
        lines.push('server {');
        lines.push(`    listen ${port};`);
        lines.push(`    server_name localhost;`);
        lines.push('');
        lines.push(`    root /var/www/${project.name}/${project.buildDir};`);
        lines.push(`    index index.html index.htm;`);
        lines.push('');
        lines.push('    # 安全 headers');
        lines.push('    add_header X-Frame-Options "SAMEORIGIN" always;');
        lines.push('    add_header X-Content-Type-Options "nosniff" always;');
        lines.push('    add_header X-XSS-Protection "1; mode=block" always;');
        lines.push('');
        
        if (project.isSPA) {
            lines.push('    # SPA 路由支持');
            lines.push('    location / {');
            lines.push('        try_files $uri $uri/ /index.html;');
            lines.push('    }');
        } else {
            lines.push('    location / {');
            lines.push('        try_files $uri $uri/ =404;');
            lines.push('    }');
        }
        
        lines.push('');
        lines.push('    # API 代理（可选）');
        lines.push('    # location /api {');
        lines.push('    #     proxy_pass http://localhost:3000;');
        lines.push('    #     proxy_http_version 1.1;');
        lines.push('    #     proxy_set_header Upgrade $http_upgrade;');
        lines.push('    #     proxy_set_header Connection "upgrade";');
        lines.push('    #     proxy_set_header Host $host;');
        lines.push('    #     proxy_set_header X-Real-IP $remote_addr;');
        lines.push('    # }');
        lines.push('');
        lines.push('    # 静态文件缓存');
        lines.push('    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {');
        lines.push('        expires 1y;');
        lines.push('        add_header Cache-Control "public, immutable";');
        lines.push('    }');
        lines.push('');
        lines.push('    error_page 500 502 503 504 /50x.html;');
        lines.push('    location = /50x.html {');
        lines.push('        root /usr/share/nginx/html;');
        lines.push('    }');
        lines.push('}');
        
        return lines;
    }

    private generateAdvancedServerBlock(project: ProjectInfo, options: any): string[] {
        const lines: string[] = [];
        
        lines.push('server {');
        lines.push(`    listen ${options.port};`);
        lines.push(`    server_name ${options.serverName || 'localhost'};`);
        lines.push('');
        lines.push(`    root /var/www/${project.name}/${project.buildDir};`);
        lines.push(`    index index.html index.htm;`);
        lines.push('');
        
        if (options.enableCors) {
            lines.push('    # CORS 跨域配置');
            lines.push('    add_header \'Access-Control-Allow-Origin\' \'*\' always;');
            lines.push('    add_header \'Access-Control-Allow-Methods\' \'GET, POST, OPTIONS, PUT, DELETE\' always;');
            lines.push('    add_header \'Access-Control-Allow-Headers\' \'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization\' always;');
            lines.push('');
        }
        
        lines.push('    # 安全 headers');
        lines.push('    add_header X-Frame-Options "SAMEORIGIN" always;');
        lines.push('    add_header X-Content-Type-Options "nosniff" always;');
        lines.push('    add_header X-XSS-Protection "1; mode=block" always;');
        lines.push('');
        
        if (project.isSPA) {
            lines.push('    # SPA 路由支持');
            lines.push('    location / {');
            lines.push('        try_files $uri $uri/ /index.html;');
            lines.push('    }');
        }
        
        if (options.enableProxy && options.proxyTarget) {
            lines.push('');
            lines.push('    # 反向代理配置');
            lines.push('    location /api/ {');
            lines.push(`        proxy_pass ${options.proxyTarget}/;`);
            lines.push('        proxy_http_version 1.1;');
            lines.push('        proxy_set_header Upgrade $http_upgrade;');
            lines.push('        proxy_set_header Connection "upgrade";');
            lines.push('        proxy_set_header Host $host;');
            lines.push('        proxy_set_header X-Real-IP $remote_addr;');
            lines.push('        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;');
            lines.push('        proxy_set_header X-Forwarded-Proto $scheme;');
            lines.push('        proxy_read_timeout 300s;');
            lines.push('        proxy_connect_timeout 75s;');
            lines.push('    }');
        }
        
        if (options.enableLoadBalance) {
            lines.push('');
            lines.push('    # 负载均衡配置');
            lines.push('    location /api/ {');
            lines.push('        proxy_pass http://backend;');
            lines.push('        proxy_http_version 1.1;');
            lines.push('        proxy_set_header Host $host;');
            lines.push('        proxy_set_header X-Real-IP $remote_addr;');
            lines.push('    }');
        }
        
        lines.push('');
        lines.push('    # 静态文件缓存');
        lines.push('    location ~* \\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {');
        lines.push('        expires 1y;');
        lines.push('        add_header Cache-Control "public, immutable";');
        lines.push('    }');
        lines.push('}');
        
        return lines;
    }

    private generateHttpsServerBlock(project: ProjectInfo, options: any): string[] {
        return [
            'server {',
            '    listen 443 ssl http2;',
            `    server_name ${options.serverName || 'localhost'};`,
            '',
            '    ssl_certificate /path/to/your/certificate.crt;',
            '    ssl_certificate_key /path/to/your/private.key;',
            '',
            '    ssl_protocols TLSv1.2 TLSv1.3;',
            '    ssl_ciphers HIGH:!aNULL:!MD5;',
            '    ssl_prefer_server_ciphers on;',
            '',
            `    root /var/www/${project.name}/${project.buildDir};`,
            '    index index.html;',
            '',
            '    location / {',
            '        try_files $uri $uri/ /index.html;',
            '    }',
            '}'
        ];
    }

    private generateUpstreamBlock(options: any): string[] {
        const servers = options.upstreamServers
            .split(',')
            .map((s: string) => s.trim())
            .filter((s: string) => s.length > 0);

        const lines: string[] = [
            '# 负载均衡上游服务器配置',
            'upstream backend {'
        ];

        servers.forEach((server: string, index: number) => {
            const weight = index === 0 ? ' weight=3' : '';
            lines.push(`    server ${server}${weight};`);
        });

        lines.push('}');
        
        return lines;
    }
}
